apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec: 
# Use hack/update-sso.sh to compute this for dev-sso auth domain 
  sso: "https://keycloak-dev-sso.apps.stoneintg436.lab.psi.pnq2.redhat.com/auth/" 
  ingressClass: openshift-default
  hostname: upi-0.stoneintg436.lab.psi.pnq2.redhat.com
