# note, the sso is a hardcoded route to enable easy access but is "guessable"
apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot 
spec:
# CHANGE ME DEPENDING ON KEYCLOAK
# infra-deployment keycloak on crc in dev-sso NS
  sso: 'https://keycloak-dev-sso.apps-crc.testing/auth/' 
# keycloak from clowder in boot NS
 # sso: 'https://keycloak-auth-boot.apps-crc.testing/auth/'
  ingressClass: openshift-default
  hostname: env-boot-local-127-0-0-1.nip.io
   