kind: Service
apiVersion: v1
metadata:  
  name: keycloak-svc
  labels:
    app: keycloak
spec:  
  ports:
    - name: keycloak
      protocol: TCP
      port: 8080
      targetPort: 8080 
  selector:
    app: keycloak
    component: keycloak 
