apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: redhat-external
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: dev-sso
  realm:
    accessTokenLifespan: 7200
    clients:
      - enabled: true
        redirectUris:
          - '*'
        clientId: cloud-services
        name: cloud-services
        implicitFlowEnabled: false
        publicClient: true
        standardFlowEnabled: true
        protocol: openid-connect
        webOrigins:
          - '*'
        directAccessGrantsEnabled: true
    displayName: Redhat External for HAC
    enabled: true
    id: rh-sso
    loginTheme: keycloak
    realm: redhat-external
    users:
      - credentials:
          - type: password
            value: john
        email: john@awesometown.ca
        emailVerified: true
        enabled: true
        firstName: john
        id: john
        username: john
