apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: hac-infra
spec:
  API:
    versions:
      - v1
  assetsPrefix: api/plugins
  deploymentRepo: 'http://github.com/openshift/hac-infra'
  envName: env-boot
  frontend:
    paths:
      - /api/plugins/hac-infra
  image: quay.io/cloudservices/hac-infra-frontend:feab95f
  title: hac-infra